#!/bin/bash

# EMAIL=$(git config --get user.email)

# if [[ $EMAIL != *"@gruposantander.com"* && $EMAIL != *"@paradigmadigital.com"* && $EMAIL != *"@openbank.com"* ]]; then

#     grep -qE '[a-zA-Z]{3}[0-9]{3}-[0-9]+' $1

#     if [[ $? != 0 ]]; then
#         echo -e "No issue specified in commit message:\n$(cat $1)\nCommit rejected"
#         exit 1
#     fi
# fi

exit 0
