#!/bin/sh
MAX_PARAMS=300

# If there are JavaScript files staged we launch eslint.
files=$(git diff --cached --name-only --diff-filter=ACMR | grep -E '.js?$' | grep -v '.test')
if [ "$files" = "" ]; then
  echo "There are no .js file staged"
else
  echo "Running ES linter..."
  if [ "${#files[@]}" -lt "$MAX_PARAMS" ]; then
    echo ${files} | xargs app/node_modules/.bin/eslint --color
  else
    node_modules/.bin/eslint --color
  fi
fi

RETVAL_ESLINT=$?

if [ $RETVAL_ESLINT -ne 0 ]; then
  echo "Can't commit: Some of your file isn't passing ES linter validation."
  exit 1
fi

# If there are Sass files staged we launch sass-lint.
files=$(git diff --cached --name-only --diff-filter=ACMR | grep -E '.scss?$')
if [ "$files" = "" ]; then
  echo "There are no .scss file staged"
else
  echo "Running Sass linter..."
  if [ "${#files[@]}" -lt "$MAX_PARAMS" ]; then
    node_modules/.bin/sass-lint -c .sass-lint.yml -v -q ${files}
  else
    node_modules/.bin/sass-lint -c .sass-lint.yml -v -q
  fi
fi

RETVAL_SASS=$?

if [ $RETVAL_SASS -ne 0 ]; then
    echo "Can't commit: Some of your file isn't passing Sass linter validation."
    exit 1
fi

# if [ $RETVAL_SASS -eq 0 ] && [ $RETVAL_ESLINT -eq 0 ]; then
#     # Running codemod
#     echo "Running Codemod scripts... cleaning code <3"
#     node_modules/.bin/jscodeshift -t react-codemod/transforms/sort-comp.js src/**/**.js

#     echo "ES and Sass linter validation passed, commiting..."
#     exit 0
# fi

# Check flow js typing errors
appPath="$(pwd)/app"
WHITE='\033[1;37m'
CYAN='\033[0;36m'
RED='\033[0;31m'

echo "${CYAN}Running Flow"
echo "${CYAN}Restarting Flow server"
echo "${WHITE}"
app/node_modules/.bin/flow stop "$appPath"
echo "${CYAN}Checking files"
echo "${WHITE}"
app/node_modules/.bin/flow "$appPath" --show-all-errors --color=always

RETVAL_FLOW=$?

if [ $RETVAL_FLOW -ne 0 ]; then
    echo "${RED}Can't commit: Some of your file isn't passing FLOW type checking validation. See above error's output"
    echo "${WHITE}"
    exit 1
fi

# exit 1
exit 0
